### ISSUE TITLE
Translation of lifetimes in Fn trait input parameters

### ISSUE THREAD

**Issue by alecmocatta** [dtolnay/async-trait#106]
I think this is a fairly niche and easy to work around case but it's a surprising footgun that might be worth a fix?

```rust
use async_trait::async_trait;
use core::future::Future;

#[async_trait]
pub trait ProcessPool: Send + Sync {
    type ThreadPool;

    async fn spawn<F, Fut, T>(&self, work: F) -> T
    where
        F: FnOnce(&Self::ThreadPool) -> Fut + Send,
        Fut: Future<Output = T> + 'static;
}

#[async_trait]
impl<P: ?Sized> ProcessPool for &P
where
    P: ProcessPool,
{
    type ThreadPool = P::ThreadPool;

    async fn spawn<F, Fut, T>(&self, work: F) -> T
    where
        F: FnOnce(&Self::ThreadPool) -> Fut + Send,
        Fut: Future<Output = T> + 'static,
    {
        (*self).spawn(work).await
    }
}
```
[Playground](https://play.rust-lang.org/?edition=2018&gist=502159c0378036ce4f089079480c43de)

`Self::ThreadPool` on line 23 is translated to `<&P as ProcessPool>::ThreadPool`. I believe due to how unnamed lifetimes are treated in the call syntax of Fn traits, this is desugared to include a HRTB? This leads to the failure:

```
expected a `std::ops::FnOnce<(&<&P as ProcessPool>::ThreadPool,)>` closure, found `F`
```

This can be resolved by translating instead to `<&'static P as ProcessPool>::ThreadPool`. I don't know if this breaks other use cases however?

**Comment by taiki-e** [comment]
> This can be resolved by translating instead to `<&'static P as ProcessPool>::ThreadPool`. I don't know if this breaks other use cases however?

IIUC this breaks use cases like [`FutureExt::inspect`](https://docs.rs/futures/0.3.5/futures/future/trait.FutureExt.html#method.inspect):

```rust
use async_trait::async_trait;
use std::future::Future;

#[async_trait]
pub trait FutureExt: Future + Send + Sync {
    async fn inspect<F>(self, f: F) -> Self::Output
    where
        F: FnOnce(&Self::Output) + Send,
        Self: Sized;
}

#[async_trait]
impl<Fut: ?Sized + Future + Send + Sync> FutureExt for Fut {
    async fn inspect<F>(self, f: F) -> Fut::Output
    where
        F: FnOnce(&Fut::Output) + Send,
        Self: Sized,
    {
        let output = self.await;
        f(&output);
        output
    }
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f8679b7749e05e6abd73d1387e9062d1)

if using `&'static`:

```diff
-         F: FnOnce(&Fut::Output) + Send,
+         F: FnOnce(&'static Fut::Output) + Send,
```

```text
error[E0310]: the associated type `<Fut as std::future::Future>::Output` may not live long enough
   --> tests/test.rs:924:12
    |
924 |         F: FnOnce(&'static Fut::Output) + Send,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7dc36baca9c7a3753a47118753cb2588)

**Comment by taiki-e** [comment]
Actually, it seems that it can be fixed by using an explicit lifetime in type `&P`, not static. (my above comment is incorrect, sorry)

```diff
- impl<P: ?Sized> ProcessPool for &P
+ impl<'a, P: ?Sized> ProcessPool for &'a P
```

```rust
use async_trait::async_trait;
use std::future::Future;

#[async_trait]
pub trait ProcessPool: Send + Sync {
    type ThreadPool;

    async fn spawn<F, Fut, T>(&self, work: F) -> T
    where
        F: FnOnce(&Self::ThreadPool) -> Fut + Send,
        Fut: Future<Output = T>;
}

#[async_trait]
impl<'a, P: ?Sized> ProcessPool for &'a P
where
    P: ProcessPool,
{
    type ThreadPool = P::ThreadPool;

    async fn spawn<F, Fut, T>(&self, work: F) -> T
    where
        F: FnOnce(&Self::ThreadPool) -> Fut + Send,
        Fut: Future<Output = T>,
    {
        (*self).spawn(work).await
    }
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=070ab7051d48d5adede95573491ed4b8)

**Comment by alecmocatta** [comment]
Thanks for the quick response and fix @taiki-e!
