### ISSUE TITLE
Don't rely on Box being in the prelude

### ISSUE THREAD

**Issue by Kestrer** [dtolnay/async-trait#132]
This code:

```rust
use async_trait::async_trait;

struct Box;

#[async_trait]
trait Foo {
    async fn foo(&self);
}

#[async_trait]
impl Foo for () {
    async fn foo(&self) {}
}
```

Fails because `async-trait` uses `Box` instead of ~~`::std::boxed::Box`~~ `::alloc::boxed::Box` in its macro expansion.

**Comment by taiki-e** [comment]
If use `::std::boxed::Box` path, cannot use async-trait on no-std environment.

**Comment by Koxiaet** [comment]
Oh, then it should use `::alloc::boxed::Box`.

**Comment by taiki-e** [comment]
Yeah, but note that `alloc` crate is not available without an explicit `extern crate alloc`.

**Comment by taiki-e** [comment]
> note that `alloc` crate is not available without an explicit `extern crate alloc`.

The way to make this works correctly is a bit tricky.
Inside functions, it's available by importing like `extern crate alloc as _alloc`, but doing the same in the position of the return value can cause `_alloc` to conflict with `_alloc` generated by other `#[async_trait]`. Probably it needs a trick, such as including the hash value of the input AST in the imported crate name.

**Comment by dtolnay** [comment]
I would like to leave this as currently implemented. Nobody should redefine Box and then expect to have boxed trait objects in the same module using a different Box.
