### ISSUE TITLE
the size for values of type `Self` cannot be known at compilation time

### ISSUE THREAD

**Issue by PonasKovas** [dtolnay/async-trait#135]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f1ef3f4e382da8479816df9be24399c1

**Comment by taiki-e** [comment]
This is not an async-trait-specific issue. `Self` needs to be `Sized` to define a trait method that returns `Self`.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=dbd230a8fa56c0689c2562b230f5a81e
