### ISSUE TITLE
0.1.47 release causes issues with clippy::items_after_statements lint

### ISSUE THREAD

**Issue by tyranron** [dtolnay/async-trait#154]
When I use something like:
```rust
#[async_trait]
impl MyTrait for Foo {
    async fn my_trait(&self) {
        const MAX: u16 = 128;
        // ...
    }

    async fn or_with_use(&self) {
        use MyError as E;
        // ...
    }
}
```

[`clippy::items_after_statements`](https://rust-lang.github.io/rust-clippy/master/index.html#items_after_statements) now complains. 

Seems that the generated code has changed in the way that top-level `use`/`const` statements are not top-level anymore in sthe expanded code.

**Comment by dtolnay** [comment]
Fixed in 0.1.48.
