### ISSUE TITLE
Help: how to work with catch_unwind.

### ISSUE THREAD

**Issue by jjeffcaii** [dtolnay/async-trait#176]
Hi:

I got a compile error when using `catch_unwind`, I don't know how to change my code to resolve this problem.

Here's a simple example:

```rust
use async_trait::async_trait;
use futures::FutureExt;

#[async_trait]
pub trait Foobar: Sync + Send + 'static {
    async fn foobar(&self);
}

pub struct FoobarImpl;

#[async_trait]
impl Foobar for FoobarImpl {
    async fn foobar(&self) {
        println!("foobar");
    }
}

async fn test(x: FoobarImpl) {
    x.foobar().catch_unwind().await; // <- cannot compile
}
```

Thanks!

**Comment by taiki-e** [comment]
the future returned by foobar is not UnwindSafe. you need to use [AssertUnwindSafe](https://doc.rust-lang.org/nightly/core/panic/struct.AssertUnwindSafe.html)

```diff
-     x.foobar().catch_unwind().await;
+     AssertUnwindSafe(x.foobar()).catch_unwind().await;
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4b4839d1331876a62d80622cb7514d0f)

**Comment by jjeffcaii** [comment]
@taiki-e It works! Thanks! 😄
