### ISSUE TITLE
Async trait is failing in new lint of rust 1.58

### ISSUE THREAD

**Issue by augustocdias** [dtolnay/async-trait#187]
I have a trait with async trait not `Send`: `#[async_trait(?Send)]` and after rust 1.58 it fails with the following lint:

https://rust-lang.github.io/rust-clippy/master/index.html#no_effect_underscore_binding

**Comment by dtolnay** [comment]
I believe this was fixed many months ago. If you're still seeing this you will need to provide a minimal compilable example that reproduces the behavior.
