### ISSUE TITLE
SmallBox?

### ISSUE THREAD

**Issue by vojtechkral** [dtolnay/async-trait#19]
Out of curiosity, might this library benefit from using [SmallBoxes](https://docs.rs/smallbox/0.7.5/smallbox/) to help reduce the overhead of boxing? (Hopefully my question isn't completely off...)

**Comment by dtolnay** [comment]
Maybe, but notice that `Pin<Box<dyn Future>>` is not interchangeable with `Pin<SmallBox<dyn Future>>` because the former can be moved around without invalidating internal references.

**Comment by vojtechkral** [comment]
Ah, that's a good point. I think that makes the idea pretty much useless - I suppose most async fns end up being self-referential futures, right?

Oh well. This can probably be closed then...
