### ISSUE TITLE
rust-analyzer expected dyn Future, found impl Future

### ISSUE THREAD

**Issue by NateLing** [dtolnay/async-trait#192]
expected `Pin<Box<dyn Future<Output = Result<usize, Error>> + Send, Global>>`, found `Pin<Box<impl Future<Output = Result<usize, Error>>, Global>>`

rustc version
rustc 1.61.0-nightly (5f3700105 2022-03-22)

**Comment by dtolnay** [comment]
I would accept a PR if there is an easy fix, but I don't plan to look into this issue. It does not sound like this would be something specific to async-trait.
