### ISSUE TITLE
Using `do yeet` in a async trait function makes the compilation fail

### ISSUE THREAD

**Issue by post-rex** [dtolnay/async-trait#198]
I understand that this may not be a high priority, I mean who knows how long this syntax will last, but it would be cool to see this work.

```rs
#![feature(yeet_expr)]

#[async_trait::async_trait]
trait Test {
    async fn test(&self) -> Result<Infallible, ()> {
        do yeet;
    }
}
```
```rs
error: expected expression
  --> src/main.rs:22:9
   |
22 |         do yeet;
   |         ^^
```

Rustc version: rustc 1.63.0-nightly (ee160f2f5 2022-05-23)
For reference: https://github.com/rust-lang/rust/issues/96373

**Comment by dtolnay** [comment]
`do yeet` is only placeholder syntax so I am not interested in supporting it.
