### ISSUE TITLE
?Send -> !Send

### ISSUE THREAD

**Issue by cavedweller** [dtolnay/async-trait#20]
`?Send` annotation should be `!Send` I believe since it's opting out of a trait bound

**Comment by dtolnay** [comment]
Hmm, the thinking here was that ?Sized is also opting out of a trait bound. ?Sized doesn't disallow using it with types that are Sized, and ?Send doesn't preclude the Self type happening to be Send.

**Comment by tyranron** [comment]
I'm preferring `?Send` over `!Send` too.

**Comment by cavedweller** [comment]
This sounds reasonable I guess since It's a implicit `Send` similar to a implicit `Size`
