### ISSUE TITLE
Using self method in default implementation is not supported

### ISSUE THREAD

**Issue by stevenroose** [dtolnay/async-trait#200]
I can't find an issue for this, but it seems that this example is not supported:
```rust
use async_trait::async_trait;

#[async_trait]
pub trait Test {
	async fn normal(&self) -> bool;

	async fn with_default(&self) -> bool {
		self.normal()
	}
}
```

**Comment by dtolnay** [comment]
For calling one async function from another async function, you need to use `await` (in general, not only inside async traits):

```rust
async fn with_default(&self) -> bool {
    self.normal().await
}
```

**Comment by stevenroose** [comment]
Is it correct that that makes the futures returned no longer `Send`?
