### ISSUE TITLE
#[allow(clippy::used_underscore_binding)]

### ISSUE THREAD

**Issue by tyranron** [dtolnay/async-trait#21]
With recent nightly Rust releases Clippy has started to complain about [`used_underscore_binding` lint](https://rust-lang.github.io/rust-clippy/master/#used_underscore_binding) in every place where `#[async_trait]` attr is used.

I believe it can be fixed with placing `#[allow(clippy::pedantic, clippy::style)]` attr on generated code.

**Comment by dtolnay** [comment]
Thanks! Fixed in 0.1.8.
