### ISSUE TITLE
The status of GAT implementation?

### ISSUE THREAD

**Issue by qiujiangkun** [dtolnay/async-trait#220]
Hi,

Since GAT is now stabilized, what's the status of GAT of async_trait?

I'm building a library that utilizes GAT heavily. It will be nice just write 
```rust
#[async_trait]
trait Foo {
    async fn foo(&self);
}
struct F;
#[async_trait]
trait Foo {
    async fn foo(&self) {}
}
```
Rather than
```rust
trait Foo {
    type Future<'a>: Future<Output = ()> + 'a;
    fn foo(&self) -> self::Future<'_>;
}
struct F;
trait Foo {
    type Future<'a> = impl Future<Output = ()> + 'a;
    fn foo(&self) -> self::Future<'_> {}
}
```

GAT can eliminate Boxes, but harder to write and not object-safe. So it's better to have an option to opt-in the GAT version.

**Comment by dtolnay** [comment]
A GAT implementation is not being considered for this crate.

**Comment by vikulikov** [comment]
> A GAT implementation is not being considered for this crate.

But why?
