### ISSUE TITLE
Filling match arms replaces #[async_trait] attribute instead of actual match statement

### ISSUE THREAD

**Issue by vikulikov** [dtolnay/async-trait#225]
Before:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/28891532/207567539-f59bdabb-b43a-47df-8815-d4c5ec311a0d.png">
After:
<img width="620" alt="image" src="https://user-images.githubusercontent.com/28891532/207567582-c509090a-43bb-4392-9103-fc6a60711273.png">

This problem occurs also in user's code when implementing the trait

**Comment by dtolnay** [comment]
This is a bug in whatever IDE you are using.

**Comment by vikulikov** [comment]
I believe it is rust-analyzer than. Because I had the same behavior in neovim also

**Comment by WhyNotHugo** [comment]
@vikulikov Did you report this on the rust_analyzer side?

**Comment by vikulikov** [comment]
No, for some reason I forgot to do that

**Comment by WhyNotHugo** [comment]
https://github.com/rust-lang/rust-analyzer/issues/12938
