### ISSUE TITLE
Support the impl Future syntax

### ISSUE THREAD

**Issue by Sytten** [dtolnay/async-trait#274]
Hi!

The crate that was promised to patch the limitations of 1.75 async trait fn (trait-variant) never took off and was never finished.

This leaves library developers that want to support both boxed and non-boxed futures in messy state since most need to do the `impl Future` to get the `Send` bound and thus can't use async-trait.

I am wondering if async-trait could support the return `impl Future<Output = ...> + Send` syntaxt to help in the transition? Or would that be a breaking change / not something you would want. Even just basic support would already be a huge improvements.

Thanks

**Comment by dtolnay** [comment]
I would prefer not to support that in this crate.

**Comment by Sytten** [comment]
Fair enough, kinda annoying that we are stuck in this state. There really no good solution to this problem right now.
