### ISSUE TITLE
`&mut self` parameters don't need `Sync` bounds

### ISSUE THREAD

**Issue by oli-cosmian** [dtolnay/async-trait#50]
Only `&self` needs `Sync` bounds, because you can create more of these references. But if you start out with `&mut self`, there's no way anyone else can have a borrow, so the additional bound is unnecessary.

**Comment by dtolnay** [comment]
I think this is already handled correctly. Can you give an example of an invocation that produces a wrong Sync bound?

There are only two places that we deal with Sync:

https://github.com/dtolnay/async-trait/blob/42aadfe85a79d2d7402bb272b8c79566b77b2c22/src/expand.rs#L176-L180

https://github.com/dtolnay/async-trait/blob/42aadfe85a79d2d7402bb272b8c79566b77b2c22/src/expand.rs#L328-L330

As you can see those are both for mutability=None receivers.

**Comment by oli-cosmian** [comment]
I was in fact confusing two very similar functions with each other. Sorry about the noise. I should have used `cargo expand`.
