### ISSUE TITLE
Any ideas on how to abstract over async closures? Can you collaborate with Diesel to bring about async?

### ISSUE THREAD

**Issue by Bajix** [dtolnay/async-trait#58]
Would you be willing to read over the [Async I/O thread](https://github.com/diesel-rs/diesel/issues/399) on Diesel? If you have any ideas on how to unblock Diesel going full async, I reckon the more full async ODM/ORMs/DB Drivers there all, and the more feature complete they become, the more compelling Rust is going to look over other languages. It feels like we're almost there, but that this is a blocker for widespread adoption in the startup space, and that once we get past this hurdle Rust will start to experience a healthy period of growth/adoption.

**Comment by dtolnay** [comment]
I skimmed the thread but it is not something that I will be able to dedicate time to. It sounds like the biggest help going forward would be funding on the language design side and the compiler implementation side to work through the remaining obstacles.
