### ISSUE TITLE
Builds targeting musl currently fail

### ISSUE THREAD

**Issue by marcelbuesing** [dtolnay/async-trait#62]
Using async-trait in builds targeting musl currently fails with the following error:
```
error: cannot produce proc-macro for `async-trait v0.1.22` as the target `x86_64-unknown-linux-musl` does not support these crate types
```

https://github.com/rust-lang/rust/issues/40174

**Comment by augustocdias** [comment]
You have to set the following to compile proc macros in musl 

```RUSTFLAGS="-C target-feature=-crt-static" cargo build ```

**Comment by dtolnay** [comment]
Closing because it doesn't seem like this is something that would be fixed in async-trait, it affects use of proc macros on musl in general. https://github.com/rust-lang/rust/issues/40174#issuecomment-580868097 looks like a promising way for the compiler to fix this across all proc macros.
