### ISSUE TITLE
Allow future to be !Send

### ISSUE THREAD

**Issue by Hexilee** [dtolnay/async-trait#70]
I hope there is a parameter in `async_trait` like:

```rust
#[async_trait(unsend)]
trait A {
    async fn do(&self);
}
```

Then return type of `A::do` will be `Pin<Box<dyn std::future::Future<Output = ()> + 'async>>` instead of `Pin<Box<dyn std::future::Future<Output = ()> + Send + 'async>>`.

**Comment by dtolnay** [comment]
Yes, look for where it talks about `?Send` in the readme.

**Comment by Hexilee** [comment]
Oh, my fault, thx.
