### ISSUE TITLE
Split into implementation and proc_macro crate

### ISSUE THREAD

**Issue by Alxandr** [dtolnay/async-trait#79]
I wanted to make a proc macro that used the `async_trait` proc macro (after doing some other changes to the input). Now, one way to do this is to require consumers to always add both (in the right order), however, I wanted to avoid that as it's not ergonomic. So I tried doing this:

```rust
use async_trait::async_trait;
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn test(_args: TokenStream, input: TokenStream) -> TokenStream {
  let cloned = input.clone();

  ::async_trait::async_trait(TokenStream::new(), input)
}
```

This does not compile, and I've not been able to figure out any way to make it work. The only thing I can think of is generating code (from my proc macro) that has `#[async_trait]` in front, but this requires consumers to explicitly have a reference to this crate, which I would also like to avoid if possible. So I suggest splitting up this crate into an "implementation" crate, using `proc-macro2`, and an actual proc_macro crate that just calls the functions exported from the implementation crate. This should be pretty straight forward to do. I'm willing to provide a PR if this is something that would be accepted.

**Comment by dtolnay** [comment]
I'll close this because I am not interested in maintaining a split setup, but the code is appropriately licensed such that someone else could maintain a fork with a non-macro entry point.

**Comment by dtolnay** [comment]
Regarding emitting code that contains an async_trait invocation, your library crate should reexport async_trait next to your own macro and your macro should emit calls to the reexport:

```rust
// alxandr/src/lib.rs
#[doc(hidden)]
pub use async_trait::async_trait;
pub use alxandr_macro::test;

// alxandr-macro/src/lib.rs
quote!(#[alxandr::async_trait])
```

**Comment by Alxandr** [comment]
Yeah, I know this is a workaround, I just wish I didn't have to use one :-/. Preferably, rust would allow calling proc-macros from proc-macros.

**Comment by dtolnay** [comment]
Me too, write an RFC. ;)
